package au.org.ala.bayesian;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
public @interface TraceDescriptor {
    /**
     * Does this object have an identity?
     * <p>
     * If true, the tracer will track the
     * </p>
     */
    boolean identify() default false;

    /**
     * An optional method that returns an identifier for the object.
     * <p>
     * The identifier method can have either zero arguments or a single {@link NetworkFactory} argument.
     * If null, an internal identifier is generated by the trace.
     * </p>
     */
    String identifier() default "";

    /**
     * The method that returns a full description of the object.
     *
     * <p>
     * The description method can have either zero arguments or a single {@link NetworkFactory} argument.
     * If null, the object itself is used.
     * </p>
     */
    String description() default "";

    /**
     * The method that returns a summary of the object.
     *
     * <p>
     * The summary method can have either zero arguments or a single {@link NetworkFactory} argument.
     * If null, either the description method is used or the object itself.
     * </p>
     */
    String summary() default "";
}
