dist: trusty
sudo: required
language: java
jdk:
- oraclejdk11
branches:
  only:
  - master
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings_simple.xml
- chmod a+x scripts/travis-setup.sh
- scripts/travis-setup.sh
- cd $TRAVIS_BUILD_DIR
script:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn -DargLine="-DTRAVIS=yes" -P travis clean install deploy; else travis_wait mvn -DargLine="-DTRAVIS=yes" -P travis clean install; fi
env:
  global:
  - TMP_DIR=/data/tmp INDEX_DIR=/data/lucene INDEX_VERSION=20230725-5 DATA_BUCKET=ala-nameindexes AWS_AP=
  - secure: s4r+YwplijkhIK4xLnnG80GoMjdI7N5kPWjJMq3jbB8Gfayeb4JwSu8kVY0fxracxrkH8/EQGDYuYMGkCgR5vgP/HlDPKG5TgHyjxrBf8oI04Lr4ARNPo0B9GZaratFMWsyMWAaBn808jAQdcdI4EYf/5+yLgz6zLDqOwc01sqIv0OMJAW44Nv2Ehsq0yO73pM7F7Z7//FOFRArENorJynuTOImYdlboxNFD3lE+tWwpIcUZFAhJzxU1i9JNky++i0sxdC3ZBA2TZjD9mm0F51Jb6yoy0G2djsUWbqjCYuDrya4yWl2ZYNUfzr3pM9bol6YdOm1n9FlkceKmu1qCowdzeEsPSmBHCke6aC2NDH3teqJ5OUvdeVD5jLnnlciFaCEhBQFCxD7WSaCnsqqLY3ZC9e6t/y4OCcOsmXI7OOlqPA64OcsWiMHpj0JMaSjctHxL6R19IUx6mPJVLX9syxgKDPGEGxt2fPuQhqKbXaVMSx4m1UYkAGMAubVMtp2V2F/wweuD7bjEw3iPWYEIbksgRj5nhy7CcjzLADZRJSmEuGpt3TL7+4l/eDQvAlCCkpfmwj+4td+vpbtYzqxL0G7vn1eDkfgIKwQepgHfD/XDtqSE2QOk57X0k9XOYi2VtWCBGONx0n1n2isJMYeSRFrqVsNEV+I9sTonfab2f3k=
  - secure: uoXxIWWRihz488x9D57Y7JnNjB1Zge39UXJSQq1B6QEljElDvPBENbVyFP1mMCu7Iyeos+Mn4daQbo4nxonCOyA1/tw8EQ1xmUFtW8ApvVpmV+8BS0A49equB+BS7RZNnIpNJPwY0bIGzbcz2ZcMc9kwwFxDMckgoAMFzq0I1NkmQtkMx8PrZly3mfDO1+H/9Nm6v8/1AuWG/WJhHZpqFKfpICE5jbkc3DZpe0gt8xfYzB9L30z+MnvqZQ08s1eS3x5ndJ19E8KFWUy8LbHeyoVpi4AM3mpsL/SPWZLp5hGlmO6Cg2xtFu2u8wfXo0L2Xwx7trCIjezdSz8N51gfanHdMsiUYcdxz2LyH5IxCbe5rqi/GI4L6P9fE767DwpvPB/8PXffBJqPghRgovDXLhNOxNWo/ipB+Mn0uvfVD+LmMp8D64O3iqy0hSeI6lyk3ZWwpYOgC/A3ZcPfYcpFhgkq2rLVqIsaY0gFJ0rdiwi55OVBN3SRkvZE+UWzP49Is4FThyWkEmLW97oHW5f6KwQAw0rtPwGULWRh/N4LwZTPpxVtXjq7yiVtbUn9KUUHHr+snYS1DdYbSQxzjF5l8QPx3A/bNbicpn0qBkeX6mE0yfNU2EPDhZGjlyvqGoWvMQry1MP5H9NyV3mtqLyI1PEU46HuxECpRxBunvrg4Fk=
